package com.rey.modelquery.tck.vnd.ins;

import jakarta.persistence.Entity;
import jakarta.persistence.Id;
import jakarta.persistence.Table;
import java.util.UUID;
import org.hibernate.annotations.UuidGenerator;

/**
 * A root whose id is generated by Hibernate's own {@code @UuidGenerator}, with no {@code @GeneratedValue}: the
 * processor must count it as generated (R-PROC-23) and the executors write it as any generated id.
 */
@Entity
@Table(name = "ins_generated_uuid")
public class InsGeneratedUuidEntity {
    @Id
    @UuidGenerator
    UUID id;

    String label;
}
