select nse1_0.id,nse1_0.sort_int,nse1_0.sort_text,nse1_0.sort_ts from nullable_sort_rows nse1_0 where nse1_0.id<=? order by 2 asc nulls last,1 fetch first ? rows only
select nse1_0.id,nse1_0.sort_int,nse1_0.sort_text,nse1_0.sort_ts from nullable_sort_rows nse1_0 where nse1_0.id<=? and (nse1_0.sort_int>? or nse1_0.sort_int is null or nse1_0.sort_int=? and nse1_0.id>?) order by 2 asc nulls last,1 fetch first ? rows only
select nse1_0.id,nse1_0.sort_int,nse1_0.sort_text,nse1_0.sort_ts from nullable_sort_rows nse1_0 where nse1_0.id<=? and (nse1_0.sort_int>? or nse1_0.sort_int is null or nse1_0.sort_int=? and nse1_0.id>?) order by 2 asc nulls last,1 fetch first ? rows only
select nse1_0.id,nse1_0.sort_int,nse1_0.sort_text,nse1_0.sort_ts from nullable_sort_rows nse1_0 where nse1_0.id<=? and (nse1_0.sort_int>? or nse1_0.sort_int is null or nse1_0.sort_int=? and nse1_0.id>?) order by 2 asc nulls last,1 fetch first ? rows only
select nse1_0.id,nse1_0.sort_int,nse1_0.sort_text,nse1_0.sort_ts from nullable_sort_rows nse1_0 where nse1_0.id<=? and (nse1_0.sort_int>? or nse1_0.sort_int is null or nse1_0.sort_int=? and nse1_0.id>?) order by 2 asc nulls last,1 fetch first ? rows only
select nse1_0.id,nse1_0.sort_int,nse1_0.sort_text,nse1_0.sort_ts from nullable_sort_rows nse1_0 where nse1_0.id<=? and (nse1_0.sort_int is null and nse1_0.id>?) order by 2 asc nulls last,1 fetch first ? rows only
select nse1_0.id,nse1_0.sort_int,nse1_0.sort_text,nse1_0.sort_ts from nullable_sort_rows nse1_0 where nse1_0.id<=? order by 2 desc nulls first,1 desc fetch first ? rows only
select nse1_0.id,nse1_0.sort_int,nse1_0.sort_text,nse1_0.sort_ts from nullable_sort_rows nse1_0 where nse1_0.id<=? and (nse1_0.sort_int is not null or nse1_0.sort_int is null and nse1_0.id<?) order by 2 desc nulls first,1 desc fetch first ? rows only
select nse1_0.id,nse1_0.sort_int,nse1_0.sort_text,nse1_0.sort_ts from nullable_sort_rows nse1_0 where nse1_0.id<=? and (nse1_0.sort_int<? or nse1_0.sort_int=? and nse1_0.id<?) order by 2 desc nulls first,1 desc fetch first ? rows only
select nse1_0.id,nse1_0.sort_int,nse1_0.sort_text,nse1_0.sort_ts from nullable_sort_rows nse1_0 where nse1_0.id<=? and (nse1_0.sort_int<? or nse1_0.sort_int=? and nse1_0.id<?) order by 2 desc nulls first,1 desc fetch first ? rows only
select nse1_0.id,nse1_0.sort_int,nse1_0.sort_text,nse1_0.sort_ts from nullable_sort_rows nse1_0 where nse1_0.id<=? and (nse1_0.sort_int<? or nse1_0.sort_int=? and nse1_0.id<?) order by 2 desc nulls first,1 desc fetch first ? rows only
select nse1_0.id,nse1_0.sort_int,nse1_0.sort_text,nse1_0.sort_ts from nullable_sort_rows nse1_0 where nse1_0.id<=? and (nse1_0.sort_int<? or nse1_0.sort_int=? and nse1_0.id<?) order by 2 desc nulls first,1 desc fetch first ? rows only
