select nse1_0.id,nse1_0.sort_int,nse1_0.sort_text,nse1_0.sort_ts from nullable_sort_rows nse1_0 where nse1_0.id<=? order by case when (nse1_0.sort_int) is null then 1 else 0 end,2,1 limit ?
select nse1_0.id,nse1_0.sort_int,nse1_0.sort_text,nse1_0.sort_ts from nullable_sort_rows nse1_0 where nse1_0.id<=? and (nse1_0.sort_int>? or nse1_0.sort_int is null or nse1_0.sort_int=? and nse1_0.id>?) order by case when (nse1_0.sort_int) is null then 1 else 0 end,2,1 limit ?
select nse1_0.id,nse1_0.sort_int,nse1_0.sort_text,nse1_0.sort_ts from nullable_sort_rows nse1_0 where nse1_0.id<=? and (nse1_0.sort_int>? or nse1_0.sort_int is null or nse1_0.sort_int=? and nse1_0.id>?) order by case when (nse1_0.sort_int) is null then 1 else 0 end,2,1 limit ?
select nse1_0.id,nse1_0.sort_int,nse1_0.sort_text,nse1_0.sort_ts from nullable_sort_rows nse1_0 where nse1_0.id<=? and (nse1_0.sort_int>? or nse1_0.sort_int is null or nse1_0.sort_int=? and nse1_0.id>?) order by case when (nse1_0.sort_int) is null then 1 else 0 end,2,1 limit ?
select nse1_0.id,nse1_0.sort_int,nse1_0.sort_text,nse1_0.sort_ts from nullable_sort_rows nse1_0 where nse1_0.id<=? and (nse1_0.sort_int>? or nse1_0.sort_int is null or nse1_0.sort_int=? and nse1_0.id>?) order by case when (nse1_0.sort_int) is null then 1 else 0 end,2,1 limit ?
select nse1_0.id,nse1_0.sort_int,nse1_0.sort_text,nse1_0.sort_ts from nullable_sort_rows nse1_0 where nse1_0.id<=? and (nse1_0.sort_int is null and nse1_0.id>?) order by case when (nse1_0.sort_int) is null then 1 else 0 end,2,1 limit ?
select nse1_0.id,nse1_0.sort_int,nse1_0.sort_text,nse1_0.sort_ts from nullable_sort_rows nse1_0 where nse1_0.id<=? order by case when (nse1_0.sort_int) is null then 0 else 1 end,2 desc,1 desc limit ?
select nse1_0.id,nse1_0.sort_int,nse1_0.sort_text,nse1_0.sort_ts from nullable_sort_rows nse1_0 where nse1_0.id<=? and (nse1_0.sort_int is not null or nse1_0.sort_int is null and nse1_0.id<?) order by case when (nse1_0.sort_int) is null then 0 else 1 end,2 desc,1 desc limit ?
select nse1_0.id,nse1_0.sort_int,nse1_0.sort_text,nse1_0.sort_ts from nullable_sort_rows nse1_0 where nse1_0.id<=? and (nse1_0.sort_int<? or nse1_0.sort_int=? and nse1_0.id<?) order by case when (nse1_0.sort_int) is null then 0 else 1 end,2 desc,1 desc limit ?
select nse1_0.id,nse1_0.sort_int,nse1_0.sort_text,nse1_0.sort_ts from nullable_sort_rows nse1_0 where nse1_0.id<=? and (nse1_0.sort_int<? or nse1_0.sort_int=? and nse1_0.id<?) order by case when (nse1_0.sort_int) is null then 0 else 1 end,2 desc,1 desc limit ?
select nse1_0.id,nse1_0.sort_int,nse1_0.sort_text,nse1_0.sort_ts from nullable_sort_rows nse1_0 where nse1_0.id<=? and (nse1_0.sort_int<? or nse1_0.sort_int=? and nse1_0.id<?) order by case when (nse1_0.sort_int) is null then 0 else 1 end,2 desc,1 desc limit ?
select nse1_0.id,nse1_0.sort_int,nse1_0.sort_text,nse1_0.sort_ts from nullable_sort_rows nse1_0 where nse1_0.id<=? and (nse1_0.sort_int<? or nse1_0.sort_int=? and nse1_0.id<?) order by case when (nse1_0.sort_int) is null then 0 else 1 end,2 desc,1 desc limit ?
